name: festim-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - setuptools<82
  - wheel<0.45
  - fenics
  - python>=3.10
  - matplotlib==3.7.1
  - pip>=20.1
  - sphinx==7.4.3
  - folium
  - numpy==1.24
  - sympy
  - sphinx-book-theme
  - sphinx-design
  - sphinxcontrib-bibtex
  - sphinx-copybutton
  - pillow
